/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import BowScript from "./script/BowScript"
import MainScenceControl from "./script/MainScenceControl"
import StartScence from "./script/StartScence"
import ArrowScript from "./script/ArrowScript"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/BowScript.js",BowScript);
		reg("script/MainScenceControl.js",MainScenceControl);
		reg("script/StartScence.js",StartScence);
		reg("script/ArrowScript.js",ArrowScript);
    }
}
GameConfig.width = 720;
GameConfig.height = 1280;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "center";
GameConfig.startScene = "startScence.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
