/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import About_Clip from "./script/About_Clip"
import About_List from "./script/About_List"
import ItemCell from "./script/ItemCell"
import About_Text from "./script/About_Text"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/About_Clip.js",About_Clip);
		reg("script/About_List.js",About_List);
		reg("script/ItemCell.js",ItemCell);
		reg("script/About_Text.js",About_Text);
    }
}
GameConfig.width = 720;
GameConfig.height = 1280;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "About_Image.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
